### ISSUE TITLE
Strange behaviour in channel editor

### ISSUE THREAD

**Issue by Tyrbiter** [nicsure/QuanshengDock#7]
I have a UV-K5 with the egzumer 0.21 firmware. Using the channel editor I found that the radio wasn't accepting the Tx frequency entered, instead it was changing it after entry, not always to the same value. Once it seemed to have what I wanted, after uploading to the radio I found that the TxOffset and offset direction were both zero for this memory channel and I was unable to correct this using Dock, so I had to correct them via the radio's keypad and menus.

It would be nice to know if this was operator error, I couldn't see a way to directly enter offset and direction in the Dock software channel editor. Of course, it might be that I should have flashed your modified firmware :)

Impressed with the application in general, a very good start.

**Comment by nicsure** [comment]
The channel editor accepts just a frequency for the TX and then works out the offset and direction behind the scenes. It is possible that the reason that's happening is due to the behaviour of the DataGrid WPF element the channel grid uses. When you edit a text cell you have to either press return to enter the change or click off the entire row, if you click to another cell in the same row it doesn't apply the changes to the cell you just edited. So if you enter the RX frequency, then click over to the TX frequency, it hasn't actually applied the RX frequency you just typed in, so when you enter the TX frequency it's calculating the offset from an incorrect RX frequency. I'm still trying to find a way around this annoying issue with it. When you enter the RX frequency, press return when you've finished and it might solve the problem when entering the TX.

**Comment by nicsure** [comment]
I believe I have fixed this now. A new release is available.

**Comment by Tyrbiter** [comment]
Thanks. I have updated and will have a play.

Is it essential to use your modified firmware, I am not sure if it breaks using the current egzumer 0.21

**Comment by ErikS-web** [comment]
Yes you do. As ....[explained in the Wiki under The radio Firmware](https://github.com/nicsure/QuanshengDock/wiki/20-%E2%80%90-The-radio-firmware)
