### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BallscrewBob** [nicsure/QuanshengDock#73]
Allow the spectrum display to work and keep the rest of the buttons active.
Maybe as an addition a routine to split the bars to produce a finer display.

**Comment by nicsure** [comment]
The spectrum mode completely disables the radio's functions during operation in order to do it as fast as possible. Spectrum mode is scanning dozens of frequencies per second, what else are you going to do with the radio during this? It doesn't havetime to do anything else.

Split the bars into what? It displays 1 bar per 1 frequency scanned, what is there to split them into?
